---
- name: Create base user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    shell: /bin/bash

- name: Allow passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
