---
- name: Backup the archon Discord bot database
  hosts: krcg_gra
  become: true
  gather_facts: false
  vars:
    username: lpanhaleux
  roles:
    - role: postgresql-backup
      pb_database: archon
