---
- name: Deploy the Codex codex-of-the-damned.org
  hosts: all
  become: true
  gather_facts: false
  vars:
    username: lpanhaleux
  roles:
    - role: register-ssl
      rs_server_name: codex-of-the-damned.org

    - role: register-ssl
      rs_server_name: www.codex-of-the-damned.org

    - role: flask-backend
      fb_package: codex-of-the-damned
      fb_uwsgi_entrypoint: "codex_of_the_damned:app"
      fb_server_name: codex-of-the-damned.org
      fb_port: 8002
      fb_env:
        PYTHONOPTIMIZE: 1

    - role: backend-website
      tags: backend
      pw_server_name: codex-of-the-damned.org
      pw_alternate_server_name: www.codex-of-the-damned.org
      pw_port: 8002
