---
- hosts: krcg
  become: "yes"
  gather_facts: "no"
  vars:
    username: lpanhaleux
  roles:
    - role: register-ssl
      rs_server_name: codex-beta.krcg.org

    - role: flask-backend
      fb_package: codex-of-the-damned
      fb_uwsgi_entrypoint: "codex_of_the_damned:app"
      fb_server_name: codex-beta.krcg.org
      fb_port: 8001

    - role: backend-website
      tags: backend
      pw_server_name: codex-beta.krcg.org
      pw_port: 8001
