---
- name: Server bootstrap
  hosts: all
  become: true
  # become_method: su
  gather_facts: false

  vars:
      username: lpanhaleux

  roles:
      - role: setup-base-user
      - role: add-pubkey
        pubkey_file: ~/.ssh/krcg_deploy.pub

  post_tasks:
      - name: Remove SSH access for root user
        ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^#?PermitRootLogin"
            line: "PermitRootLogin no"
      - name: Restart SSH
        ansible.builtin.service:
            name: ssh
            state: restarted
