---
- hosts: krcg
  become: "yes"
  gather_facts: "no"
  vars:
      username: lpanhaleux
  roles:
      - role: register-ssl
        rs_server_name: static.krcg.org

      - role: static-website
        sw_server_name: static.krcg.org
        sw_cache: true
        sw_autoindex: true
