---
- name: Deploy static.krcg.org
  hosts: all
  become: true
  gather_facts: false
  vars:
      username: lpanhaleux
  roles:
      - role: register-ssl
        rs_server_name: static.krcg.org

      - role: static-website
        sw_server_name: static.krcg.org
        sw_cache: true
        sw_cachebust: true
        sw_autoindex: true
