---
- hosts: krcg
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: lpanhaleux
  roles:
    - role: register-ssl
      tags: backend
      rs_server_name: api.krcg.org

    - role: flask-backend
      tags:
      - backend
      - uwsgi
      fb_package: krcg
      fb_repository: lionel-panhaleux/krcg
      fb_pip_target: ".[web]"
      fb_uwsgi_entrypoint: "src.wsgi:application"
      fb_server_name: api.krcg.org
      fb_port: 8000
      fb_env: {}

    - role: backend-website
      tags: backend
      pw_server_name: api.krcg.org
      pw_port: 8000
