---
- hosts: krcg
  become: 'yes'
  gather_facts: 'no'
  vars:
    username: lpanhaleux
  roles:
    - role: register-ssl
      rs_server_name: images.krcg.org

    - role: static-website
      sw_server_name: images.krcg.org
