---
- name: Deploy the KRCG API on api.krcg.org
  hosts: all
  become: true
  gather_facts: false
  vars:
      username: lpanhaleux
  roles:
      - role: register-ssl
        rs_server_name: api.krcg.org

      - role: flask-backend
        fb_package: krcg-api
        fb_uwsgi_entrypoint: "krcg_api.wsgi:application"
        fb_server_name: api.krcg.org
        fb_port: 8003
        fb_env:
            PYTHONOPTIMIZE: 1

      - role: backend-website
        tags: backend
        pw_server_name: api.krcg.org
        pw_port: 8003
