---
- hosts: all
  become: true
  gather_facts: false
  vars:
    username: lpanhaleux
  roles:
    - role: setup-packages
- hosts: all
  gather_facts: false
  vars:
    username: lpanhaleux
  roles:
    - role: create-ssh-key
