---
- name: Add HTTP site configuration
  ansible.builtin.template:
    src: http.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ r.server_name }}.http.conf"
    mode: '644'

- name: Reload nginx
  tags:
    - nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Let certbot generate a certificate and serve it
  tags:
    - certs
  ansible.builtin.command: "certbot certonly --webroot --email {{ r.contact_name }} --agree-tos --staple-ocsp --webroot-path=/usr/share/nginx/html -d {{ r.server_name }}"
  args:
    creates: "/etc/letsencrypt/live/{{ r.server_name }}/fullchain.pem"

- name: Ensure certbot renewal hook directory exists
  tags:
    - certs
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/deploy
    state: directory
    mode: '0755'

- name: Ensure certbot renewal reloads nginx
  tags:
    - certs
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh
    content: |
      #!/bin/bash
      systemctl reload nginx
    mode: '0755'
