---
- name: Add HTTPS site configuration
  ansible.builtin.template:
    src: https.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ r.server_name }}.https.conf"

- name: Reload nginx
  tags:
    - deploy
    - certs
  ansible.builtin.service:
    name: nginx
    state: reloaded
