---
- name: Ensure site root folder is present
  ansible.builtin.file:
    state: directory
    path: "{{ r.site_root }}/dist"
    owner: "{{ username }}"
    mode: '755'

- name: Add HTTPS site configuration
  ansible.builtin.template:
    src: https.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ r.server_name }}.https.conf"
    mode: '644'

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
